---
title: "Week 6 Practice"
author: "Amy Richardson"
date: "2/19/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(Rcmdr)
install.packages("QuantPsyc")
library(QuantPsyc)
```


Read in Data
```{r}
album2 <- read.delim("Album Sales 2.dat", header = TRUE)
```

Create two models. 
  1. Adverts as predictors
  2. Adverts, Airplay, and Attrativeness as predictors
```{r}
albumSales.2 <- lm(sales ~ adverts, data = album2)

albumSales.3 <- lm(sales ~ adverts + airplay + attract, data = album2)
```
  
Model Summaries
```{r}
summary(albumSales.2)
summary(albumSales.3)
```
Find standardized b-values
```{r}
lm.beta(albumSales.3)

```

Calculate Confidence intervals
```{r}
confint(albumSales.3)
```

Compare models using ANOVA
```{r}
anova(albumSales.2, albumSales.3)
```
Run casewise diagnostics and add to new column in dataframe
```{r}
album2$residuals<-resid(albumSales.3)
album2$standardized.residuals <- rstandard(albumSales.3)
album2$studentized.residuals <- rstudent(albumSales.3)
album2$cooks.distance<-cooks.distance(albumSales.3)
album2$dfbeta <- dfbeta(albumSales.3)
album2$dffit <- dffits(albumSales.3)
album2$leverage <- hatvalues(albumSales.3)
album2$covariance.ratios <- covratio(albumSales.3)
```
























